openapi: 3.0.0
info:
  title: Meshery Cloud
  description: Documentation for meshery Cloud REST APIs
  contact:
    email: support@layer5.io
  version: v0.6.394
servers:
  - url: https://meshery.layer5.io
    description: Meshery Cloud production server URL
  - url: https://staging-meshery.layer5.io
    description: Meshery Cloud staging server URL
  - url: http://localhost:9876
    description: Meshery Cloud development server URL (controlled via PORT environment variable)
security:
  - jwt: []
tags:
  - name: applications
    description: APIs for applications
paths:
  /api/content/applications:
    post:
      tags:
        - applications
      operationId: UpsertApplication
      summary: Upsert Application
      description: It will insert the application if not present else it will update the matching entry
      requestBody:
        $ref: '#/components/requestBodies/mesheryApplicationRequestBody'
      responses:
        '200':
          description: Upserted application
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/mesheryApplication'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '500':
          $ref: '#/components/responses/500'
    get:
      tags:
        - applications
      operationId: GetApplications
      summary: Get Applications
      description: Get paginated applications
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/page_size'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/order'
      responses:
        '200':
          description: Applications
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mesheryApplicationPage'
        '401':
          $ref: '#/components/responses/401'
        '500':
          $ref: '#/components/responses/500'
  /api/content/applications/upload/{id}:
    post:
      tags:
        - applications
      operationId: UpsertApplicationSourceContent
      summary: Upsert application source content
      description: Upserts only application source content
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        description: Body for upserting meshery application source content
        required: true
        content:
          text/plain:
            schema:
              $ref: '#/components/schemas/mesheryApplication/properties/source_content'
      responses:
        '200':
          $ref: '#/components/responses/200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '500':
          $ref: '#/components/responses/500'
  /api/content/applications/download/{id}:
    get:
      tags:
        - applications
      operationId: GetApplicationSourceContent
      summary: Get application source content
      description: Get application source content
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: application source content associated with ID
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/mesheryApplication/properties/source_content'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '500':
          $ref: '#/components/responses/500'
  /api/content/applications/{id}:
    get:
      tags:
        - applications
      operationId: GetApplication
      summary: Get application by ID
      description: Get application by ID
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: application associated with ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mesheryApplication'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    delete:
      tags:
        - applications
      operationId: DeleteApplication
      summary: Delete application by ID
      description: Delete application associated with ID
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Deleted application
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mesheryApplication'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
components:
  securitySchemes:
    jwt:
      type: http
      scheme: Bearer
      bearerFormat: JWT
  schemas:
    mesheryApplication:
      properties:
        id:
          $ref: '#/components/schemas/id'
        user_id:
          $ref: '#/components/schemas/id'
        application_file:
          $ref: '#/components/schemas/text'
          description: Application file
        name:
          $ref: '#/components/schemas/text'
          description: Pattern Name
        location:
          $ref: '#/components/schemas/map_object'
        visibility:
          $ref: '#/components/schemas/text'
        source_type:
          enum:
            - k8s_manifest
            - docker_compose
            - helm_chart
          description: Source type (K8s manifest, Helm chart, Docker compose)
        source_content:
          type: string
          format: byte
          description: Source content
        catalog_data:
          $ref: '#/components/schemas/map_object'
        created_at:
          $ref: '#/components/schemas/time'
        updated_at:
          $ref: '#/components/schemas/time'
    mesheryApplicationPage:
      allOf:
        - $ref: '#/components/schemas/resultsPage'
        - type: object
          properties:
            applications:
              type: array
              items:
                $ref: '#/components/schemas/mesheryApplication'
    resultsPage:
      discriminator:
        propertyName: resultType
      properties:
        page:
          type: integer
          x-go-type-skip-optional-pointer: true
        page_size:
          type: integer
          x-go-type-skip-optional-pointer: true
        total_count:
          type: integer
          x-go-type-skip-optional-pointer: true
        resultType:
          type: string
          x-go-type-skip-optional-pointer: true
      x-go-type-skip-optional-pointer: true
    id:
      type: string
      format: uuid
      x-go-type: uuid.UUID
      x-go-type-import:
        path: github.com/gofrs/uuid
      x-oapi-codegen-extra-tags:
        db: id
        json: id
      x-go-name: ID
      x-go-type-skip-optional-pointer: true
    text:
      type: string
      x-go-type-skip-optional-pointer: true
    map_object:
      type: object
      additionalProperties:
        type: string
      x-go-type-skip-optional-pointer: true
    time:
      type: string
      format: date-time
      x-go-type-skip-optional-pointer: true
  requestBodies:
    mesheryApplicationRequestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              url:
                $ref: '#/components/schemas/text'
              path:
                $ref: '#/components/schemas/text'
              save:
                type: boolean
              application_data:
                $ref: '#/components/schemas/mesheryApplication'
              source_type:
                $ref: '#/components/schemas/text'
  parameters:
    page:
      name: page
      in: query
      description: Get reponses by page
      schema:
        type: string
    page_size:
      name: page_size
      in: query
      description: Get reponses by pageSize
      schema:
        type: string
    search:
      name: search
      in: query
      description: Get responses that match search param value
      schema:
        type: string
    order:
      name: order
      in: query
      description: Get ordered responses
      schema:
        type: string
    id:
      name: id
      in: path
      description: Unique identifier
      schema:
        type: string
      required: true
  responses:
    '200':
      description: ok
      content:
        text/plain:
          schema:
            type: string
    '400':
      description: Invalid request body or request param
      content:
        text/plain:
          schema:
            type: string
    '401':
      description: Expired JWT token used or insufficient privilege
      content:
        text/plain:
          schema:
            type: string
    '404':
      description: Result not found
      content:
        text/plain:
          schema:
            type: string
    '500':
      description: Internal server error
      content:
        text/plain:
          schema:
            type: string
