# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: patterns
output: models/patterns.go
generate:
  models: true
import-mapping:
  "#/components/schemas/catalog_data": "github.com/layer5io/meshkit/models/catalog/v1alpha1"
  "./common/core.yml": "github.com/meshery/schemas/common"

output-options:
  # to make sure that all types are generated
  skip-prune: true
  include-tags: 
  - patterns
  
