openapi: 3.0.0
info:
  title: Meshmodels API
  description: API for registering and exporting mesh models
  version: 1.0.0

paths:
  /api/meshmodels/register:
    post:
      summary: Register mesh models
      operationId: RegisterMeshmodels
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ImportRequest'
      responses:
        '200':
          description: Successful registration
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Invalid request format
        '500':
          description: Internal server error

  /api/meshmodels/export:
    get:
      summary: Export a mesh model
      operationId: ExportModel
      parameters:
        - in: query
          name: id
          schema:
            type: string
          required: true
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: version
          schema:
            type: string
        - in: query
          name: output_format
          schema:
            type: string
            enum: [json, yaml, oci]
            default: oci
        - in: query
          name: file_type
          schema:
            type: string
            enum: [oci, tar, gzip]
            default: oci
      responses:
        '200':
          description: Successful export
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid request format
        '500':
          description: Internal server error

components:
  schemas:
    ImportRequest:
      type: object
      required:
        - importBody
        - uploadType  
        - register   
      properties:
        importBody:
          $ref: '#/components/schemas/ImportBody'
        uploadType:
          type: string
        register:
          type: boolean
          nullable: false  

    ImportBody:   
      type: object
      required:
        - model_file
        - url
        - file_name
      properties:
        model_file:
          type: string
          format: byte  
          description: "This represents the binary content of the file as a byte array"
        url:
          type: string
          
        file_name:
          type: string
          
