openapi: 3.0.0
components:
  schemas:
    model_definition:
      $ref: ../v1beta1/model.json
    component_definition:
      $ref: ../v1beta1/component.json
    relationship_definition:
      $ref: ../v1alpha3/relationship.json