openapi: 3.0.0
info:
  title: Meshery Relationship Evaluation API
  version: 1.0.0
  description: API for evaluating relationships in Meshery designs

paths:
  /evaluate:
    post:
      summary: Evaluate relationships in a design
      description: Performs relationship evaluation on a given design, applying policies and updating components and relationships as needed.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EvaluationRequest"
      responses:
        "200":
          description: Successful evaluation
          content:
            application/json:
              schema:
                $ref: "https://schemas.meshery.io/evaluationResponse.json"
        "400":
          description: Bad request
        "500":
          description: Internal server error

components:
  schemas:
    EvaluationRequest:
      type: object
      required:
        - design
      properties:
        design:
          $ref: "#/components/schemas/Design"
        options:
          type: object
          properties:
            returnDiffOnly:
              type: boolean
              description: If true, only return the diff of changes instead of the complete updated design
            enableTrace:
              type: boolean
              description: If true, include detailed trace information in the response

