name: Schemas Publisher
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - README.md
jobs:
  resolve-and-update-schema:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: 'master'
      - name: Install Redocly
        uses: actions/setup-node@v4
      - run: npm i -g @redocly/cli@latest
      - name: Run Script
        shell: bash
        run: |
         chmod +x ./scripts/merge-openapi-specs.sh
         ./scripts/merge-openapi-specs.sh
